ln -s colors red
ln -s colors orange
ln -s colors yellow
ln -s colors green
ln -s colors blue
ln -s colors purple
ln -s colors pink
ln -s colors white
ln -s colors cyan
ln -s colors darkgray
ln -s colors lightgray
ln -s colors gray
ln -s colors lightred
ln -s colors lightgreen
ln -s colors lightblue
ln -s colors lightcyan
ln -s colors black
